title: "Machine Learning Notes"
description: "A comprehensive collection of machine learning concepts, lectures, and hands-on projects."
remote_theme: tomjoht/documentation-theme-jekyll
url: "https://sanjanb.github.io"
baseurl: "/machine-learning"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
author: "Sanjan B M"
social:
  name: "Sanjan B M"
  links:
    - "https://github.com/sanjanb"
# google_analytics: "G-XXXXXXXXXX"
sidebar:
  nav: sidebar
